name: End-to-end tests (mobile)
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run --config viewportWidth=410 viewportHeight=860
        uses: cypress-io/github-action@v6